"""added test

Revision ID: 9ea7400a848e
Revises: 
Create Date: 2019-03-01 17:00:52.344949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea7400a848e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('current1', sa.Float(), nullable=False),
    sa.Column('current2', sa.Float(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('realP1', sa.Float(), nullable=False),
    sa.Column('realP2', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('time'),
    sa.UniqueConstraint('time')
    )
    op.create_table('tests',
    sa.Column('tests', sa.String(length=120), nullable=False),
    sa.Column('testf', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('tests'),
    sa.UniqueConstraint('tests')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    op.drop_table('measurements')
    # ### end Alembic commands ###
