"""empty message

Revision ID: aa4edd25b610
Revises: 3f5b36e8973d
Create Date: 2019-03-13 00:26:29.131036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4edd25b610'
down_revision = '3f5b36e8973d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appliances',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appliances')
    # ### end Alembic commands ###
