"""empty message

Revision ID: d14610948c0a
Revises: aa4edd25b610
Create Date: 2019-03-13 01:02:18.042674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14610948c0a'
down_revision = 'aa4edd25b610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appliances', sa.Column('power', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appliances', 'power')
    # ### end Alembic commands ###
